
/*左侧列表*/
/*window.onload=function(){
    var rb=document.getElementsByClassName("t-form");
    rb[0].style.display="block";
    rb[1].style.display="none";
    rb[2].style.display="none";
    rb[3].style.display="none";
    rb[4].style.display="none";
    rb[5].style.display="none";
    rb[6].style.display="none";
    jp.onclick=function(){
        rb[0].style.display="block";
        rb[1].style.display="none";
        rb[2].style.display="none";
        rb[3].style.display="none";
        rb[4].style.display="none";
        rb[5].style.display="none";
        rb[6].style.display="none";
    }
    hcp.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="block";
        rb[2].style.display="none";
        rb[3].style.display="none";
        rb[4].style.display="none";
        rb[5].style.display="none";
        rb[6].style.display="none";
    }
    jdkz.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="none";
        rb[2].style.display="block";
        rb[3].style.display="none";
        rb[4].style.display="none";
        rb[5].style.display="none";
        rb[6].style.display="none";
    }
    lydj.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="none";
        rb[2].style.display="none";
        rb[3].style.display="block";
        rb[4].style.display="none";
        rb[5].style.display="none";
        rb[6].style.display="none";
    }
    mp.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="none";
        rb[2].style.display="none";
        rb[3].style.display="none";
        rb[4].style.display="block";
        rb[5].style.display="none";
        rb[6].style.display="none";
    }
    qz.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="none";
        rb[2].style.display="none";
        rb[3].style.display="none";
        rb[4].style.display="none";
        rb[5].style.display="block";
        rb[6].style.display="none";
    }
    lxyc.onclick=function(){
        rb[0].style.display="none";
        rb[1].style.display="none";
        rb[2].style.display="none";
        rb[3].style.display="none";
        rb[4].style.display="none";
        rb[5].style.display="none";
        rb[6].style.display="block";
    }
}*/
/*机票列表 */
/*window.onload=function(){
    var xb=document.getElementsByClassName("second-form");
    xb[0].style.display="block";
    xb[1].style.display="none";
    xb[2].style.display="none";
    xb[3].style.display="none";
    gn.onclick=function(){
        xb[0].style.display="block";
        xb[1].style.display="none";
        xb[2].style.display="none";
        xb[3].style.display="none";
    }
    gj.onclick=function(){
        xb[0].style.display="none";
        xb[1].style.display="block";
        xb[2].style.display="none";
        xb[3].style.display="none";
    }/*
    gnt.onclick=function(){
        xb[0].style.display="none";
        xb[1].style.display="none";
        xb[2].style.display="block";
        xb[3].style.display="none";
    }
    gjt.onclick=function(){
        xb[0].style.display="none";
        xb[1].style.display="none";
        xb[2].style.display="none";
        xb[3].style.display="block";
    }
}*/
/*左侧列表*/
